### ISSUE TITLE
User Stories Part 1

### ISSUE THREAD

**Issue by NewDeLi** [tatjanafichtner/Companion-App#2]
- [ ] Als User möchte ich auf der "Code Buddy"-Seite alle Code Buddy Paare sehen, damit ich weiß, wer mit wem zusammenarbeitet.
- [ ] Als User möchte ich auf der "Teams"-Seite alle Teams sehen, damit ich weiß, wer in welchem Team arbeitet.
- [ ] Als User möchte ich auf der "Energy"-Seite mein Energie-Level mit dem der anderen Studis vergleichen, damit ich weiß ob ich mehr schlafen muss.
- [ ] Als User möchte ich auf der "Energy"-Seite mein aktuelles Energielevel bewerten, damit es in der Statistik erfasst werden kann.

**Comment by tatjanafichtner** [comment]
False
